import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import styles from './main.module.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'My App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body >
        <div className={styles.bodyBackground}>
          <div className={styles.noise}>
            {children}
          </div>
        </div>
        
      
      
      
      </body>
    </html>
  )
}
